services:
  web: 
    build:
      context: .
    ports: 
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=btredb
      - POSTGRES_PASSWORD=password
    healthcheck:
          test: ["CMD-SHELL", "pg_isready -U postgres"]
          interval: 5s
          timeout: 5s
          retries: 5